language: python


python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - "pypy"
  - "pypy3"

before_install:

 - sudo apt-get update
 - sudo apt-get install build-essential
 - pip install --upgrade pip

install:
 - python setup.py install

script:
 - python setup.py test

notifications:
  email: false
